/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../../../public/models/house-water-transformed.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['house_water-2_1']: THREE.Mesh
    ['house_water-2_2']: THREE.Mesh
    ['house_water-2_3']: THREE.Mesh
    ['house_water-2_4']: THREE.Mesh
    ['house_water-2_5']: THREE.Mesh
    ['house_water-2_6']: THREE.Mesh
    ['house_water-2_7']: THREE.Mesh
    ['house_water-2_8']: THREE.Mesh
    ['house_water-2_9']: THREE.Mesh
    ['house_water-2_10']: THREE.Mesh
    ['house_water-2_11']: THREE.Mesh
    ['house_water-2_12']: THREE.Mesh
    ['house_water-2_13']: THREE.Mesh
    ['house_water-2_14']: THREE.Mesh
    ['house_water-2_15']: THREE.Mesh
    ['house_water-2_16']: THREE.Mesh
    ['house_water-2_17']: THREE.Mesh
    ['house_water-2_18']: THREE.Mesh
    ['house_water-2_19']: THREE.Mesh
    ['house_water-2_20']: THREE.Mesh
    ['house_water-2_21']: THREE.Mesh
    ['house_water-2_22']: THREE.Mesh
    ['house_water-2_23']: THREE.Mesh
    ['house_water-2_24']: THREE.Mesh
    ['house_water-2_25']: THREE.Mesh
    ['house_water-2_26']: THREE.Mesh
    ['house_water-2_27']: THREE.Mesh
    ['house_water-2_28']: THREE.Mesh
    ['house_water-2_29']: THREE.Mesh
    ['house_water-2_30']: THREE.Mesh
    ['house_water-2_31']: THREE.Mesh
    ['house_water-2_32']: THREE.Mesh
    ['house_water-2_33']: THREE.Mesh
    ['house_water-2_34']: THREE.Mesh
    ['house_water-2_35']: THREE.Mesh
    ['house_water-2_36']: THREE.Mesh
    ['house_water-2_37']: THREE.Mesh
    ['house_water-2_38']: THREE.Mesh
    ['house_water-2_39']: THREE.Mesh
    ['house_water-2_40']: THREE.Mesh
    ['house_water-2_41']: THREE.Mesh
    ['house_water-2_42']: THREE.Mesh
    ['house_water-2_43']: THREE.Mesh
    ['house_water-2_44']: THREE.Mesh
    ['house_water-2_45']: THREE.Mesh
    ['house_water-2_46']: THREE.Mesh
    ['house_water-2_47']: THREE.Mesh
    ['house_water-2_48']: THREE.Mesh
    ['house_water-2_49']: THREE.Mesh
    ['house_water-2_50']: THREE.Mesh
    ['house_water-2_51']: THREE.Mesh
    ['house_water-2_52']: THREE.Mesh
    ['house_water-2_53']: THREE.Mesh
    ['house_water-2_54']: THREE.Mesh
    ['house_water-2_55']: THREE.Mesh
    ['house_water-2_56']: THREE.Mesh
    ['house_water-2_57']: THREE.Mesh
    ['house_water-2_58']: THREE.Mesh
    ['house_water-2_59']: THREE.Mesh
    ['house_water-2_60']: THREE.Mesh
    ['house_water-2_61']: THREE.Mesh
    ['house_water-2_62']: THREE.Mesh
    ['house_water-2_63']: THREE.Mesh
    ['house_water-2_64']: THREE.Mesh
    ['house_water-2_65']: THREE.Mesh
    ['house_water-2_66']: THREE.Mesh
    ['house_water-2_67']: THREE.Mesh
    ['house_water-2_68']: THREE.Mesh
    ['house_water-2_69']: THREE.Mesh
    ['house_water-2_70']: THREE.Mesh
    ['house_water-2_71']: THREE.Mesh
    ['house_water-2_72']: THREE.Mesh
    ['house_water-2_73']: THREE.Mesh
    ['house_water-2_74']: THREE.Mesh
    ['house_water-2_75']: THREE.Mesh
    ['house_water-2_76']: THREE.Mesh
    ['house_water-2_77']: THREE.Mesh
    ['house_water-2_78']: THREE.Mesh
    ['house_water-2_79']: THREE.Mesh
    ['house_water-2_80']: THREE.Mesh
    ['house_water-2_81']: THREE.Mesh
    ['house_water-2_82']: THREE.Mesh
    ['house_water-2_83']: THREE.Mesh
    ['house_water-2_84']: THREE.Mesh
    ['house_water-2_85']: THREE.Mesh
    ['house_water-2_86']: THREE.Mesh
    ['house_water-2_87']: THREE.Mesh
    ['house_water-2_88']: THREE.Mesh
    ['house_water-2_89']: THREE.Mesh
    ['house_water-2_90']: THREE.Mesh
    ['house_water-2_91']: THREE.Mesh
    ['house_water-2_92']: THREE.Mesh
    ['house_water-2_93']: THREE.Mesh
    ['house_water-2_94']: THREE.Mesh
    ['house_water-2_95']: THREE.Mesh
    ['house_water-2_96']: THREE.Mesh
    ['house_water-2_97']: THREE.Mesh
    ['house_water-2_98']: THREE.Mesh
    ['house_water-2_99']: THREE.Mesh
    ['house_water-2_100']: THREE.Mesh
    ['house_water-2_101']: THREE.Mesh
    ['house_water-2_102']: THREE.Mesh
    ['house_water-2_103']: THREE.Mesh
    ['house_water-2_104']: THREE.Mesh
    ['house_water-2_105']: THREE.Mesh
    ['house_water-2_106']: THREE.Mesh
    ['house_water-2_107']: THREE.Mesh
    ['house_water-2_108']: THREE.Mesh
    ['house_water-2_109']: THREE.Mesh
    ['house_water-2_110']: THREE.Mesh
    ['house_water-2_111']: THREE.Mesh
    ['house_water-2_112']: THREE.Mesh
    ['house_water-2_113']: THREE.Mesh
    ['house_water-2_114']: THREE.Mesh
    ['house_water-2_115']: THREE.Mesh
    ['house_water-2_116']: THREE.Mesh
    ['house_water-2_117']: THREE.Mesh
    ['house_water-2_118']: THREE.Mesh
    ['house_water-2_119']: THREE.Mesh
    ['house_water-2_120']: THREE.Mesh
    ['house_water-2_121']: THREE.Mesh
    ['house_water-2_122']: THREE.Mesh
    ['house_water-2_123']: THREE.Mesh
    ['house_water-2_124']: THREE.Mesh
    ['house_water-2_125']: THREE.Mesh
    ['house_water-2_126']: THREE.Mesh
    ['house_water-2_127']: THREE.Mesh
    ['house_water-2_128']: THREE.Mesh
    ['house_water-2_129']: THREE.Mesh
    ['house_water-2_130']: THREE.Mesh
    ['house_water-2_131']: THREE.Mesh
    ['house_water-2_132']: THREE.Mesh
    ['house_water-2_133']: THREE.Mesh
    ['house_water-2_134']: THREE.Mesh
    ['house_water-2_135']: THREE.Mesh
    ['house_water-2_136']: THREE.Mesh
    ['house_water-2_137']: THREE.Mesh
    ['house_water-2_138']: THREE.Mesh
    ['house_water-2_139']: THREE.Mesh
    ['house_water-2_140']: THREE.Mesh
    ['house_water-2_141']: THREE.Mesh
    ['house_water-2_142']: THREE.Mesh
    ['house_water-2_143']: THREE.Mesh
    ['house_water-2_144']: THREE.Mesh
    ['house_water-2_145']: THREE.Mesh
    ['house_water-2_146']: THREE.Mesh
    ['house_water-2_147']: THREE.Mesh
    ['house_water-2_148']: THREE.Mesh
    ['house_water-2_149']: THREE.Mesh
    ['house_water-2_150']: THREE.Mesh
    ['house_water-2_151']: THREE.Mesh
    ['house_water-2_152']: THREE.Mesh
    ['house_water-2_153']: THREE.Mesh
    ['house_water-2_154']: THREE.Mesh
    ['house_water-2_155']: THREE.Mesh
    ['house_water-2_156']: THREE.Mesh
    ['house_water-2_157']: THREE.Mesh
    ['house_water-2_158']: THREE.Mesh
    ['house_water-2_159']: THREE.Mesh
    ['house_water-2_160']: THREE.Mesh
    ['house_water-2_161']: THREE.Mesh
    ['house_water-2_162']: THREE.Mesh
    ['house_water-2_163']: THREE.Mesh
    ['house_water-2_164']: THREE.Mesh
    ['house_water-2_165']: THREE.Mesh
    ['house_water-2_166']: THREE.Mesh
    ['house_water-2_167']: THREE.Mesh
    ['house_water-2_168']: THREE.Mesh
    ['house_water-2_169']: THREE.Mesh
    ['house_water-2_170']: THREE.Mesh
    ['house_water-2_171']: THREE.Mesh
    ['house_water-2_172']: THREE.Mesh
    ['house_water-2_173']: THREE.Mesh
  }
  materials: {
    ground_1: THREE.MeshStandardMaterial
    wall_1_2: THREE.MeshStandardMaterial
    room_58_344: THREE.MeshStandardMaterial
    Railing: THREE.MeshStandardMaterial
    ['390']: THREE.MeshStandardMaterial
    ['396']: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
    grey: THREE.MeshStandardMaterial
    flltgrey: THREE.MeshStandardMaterial
    ltgrey: THREE.MeshStandardMaterial
    white_409: THREE.MeshStandardMaterial
    yellowbrt: THREE.MeshStandardMaterial
    flltgrey_sweethome3d_window_pane_420: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    lighttan: THREE.MeshStandardMaterial
    white_Cube_2_1_433: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Lock: THREE.MeshStandardMaterial
    Frame_in: THREE.MeshStandardMaterial
    white_Fenetre_480: THREE.MeshStandardMaterial
    None: THREE.MeshStandardMaterial
    white_13_526: THREE.MeshStandardMaterial
    flesh: THREE.MeshStandardMaterial
    glassblutint: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    cuero_granate: THREE.MeshStandardMaterial
    patas_metal: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    black_615: THREE.MeshStandardMaterial
    white_618: THREE.MeshStandardMaterial
    Oriental_rug: THREE.MeshStandardMaterial
    carpet_627: THREE.MeshStandardMaterial
    gray: THREE.MeshStandardMaterial
    Bathmat: THREE.MeshStandardMaterial
    flbrown: THREE.MeshStandardMaterial
    brownskn: THREE.MeshStandardMaterial
    ['636']: THREE.MeshStandardMaterial
    Material_LakeMoraine: THREE.MeshStandardMaterial
    Aluminium: THREE.MeshStandardMaterial
    ['640']: THREE.MeshStandardMaterial
    ['643']: THREE.MeshStandardMaterial
    Picture_1: THREE.MeshStandardMaterial
    Picture_5: THREE.MeshStandardMaterial
    ['651']: THREE.MeshStandardMaterial
    Aluminium_652: THREE.MeshStandardMaterial
    Material_Etretat: THREE.MeshStandardMaterial
    black_656: THREE.MeshStandardMaterial
    cueEnd: THREE.MeshStandardMaterial
    ['658']: THREE.MeshStandardMaterial
    cueFront: THREE.MeshStandardMaterial
    cueBrass: THREE.MeshStandardMaterial
    cueRubber: THREE.MeshStandardMaterial
    cueTip: THREE.MeshStandardMaterial
    ballCue: THREE.MeshStandardMaterial
    ballN1: THREE.MeshStandardMaterial
    ballN2: THREE.MeshStandardMaterial
    ballN3: THREE.MeshStandardMaterial
    ballN4: THREE.MeshStandardMaterial
    ballN5: THREE.MeshStandardMaterial
    ballN6: THREE.MeshStandardMaterial
    ballN7: THREE.MeshStandardMaterial
    ballN8: THREE.MeshStandardMaterial
    ballN9: THREE.MeshStandardMaterial
    ballN10: THREE.MeshStandardMaterial
    ballN11: THREE.MeshStandardMaterial
    ballN15: THREE.MeshStandardMaterial
    ballN14: THREE.MeshStandardMaterial
    ballN13: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ballN12: THREE.MeshStandardMaterial
    felt: THREE.MeshStandardMaterial
    GrisClair: THREE.MeshStandardMaterial
    BoisClair: THREE.MeshStandardMaterial
    METAL_brass_polish: THREE.MeshStandardMaterial
    METAL_aluminum: THREE.MeshStandardMaterial
    GLASS: THREE.MeshStandardMaterial
    PAINT_gloss_white: THREE.MeshStandardMaterial
    Feet: THREE.MeshStandardMaterial
    Material_Cube_787: THREE.MeshStandardMaterial
    sofa: THREE.MeshStandardMaterial
    negrepotes: THREE.MeshStandardMaterial
    metall: THREE.MeshStandardMaterial
    archwhite: THREE.MeshStandardMaterial
    sweethome3d_window_mirror_902: THREE.MeshStandardMaterial
    aqua: THREE.MeshStandardMaterial
    Rectangle04_1: THREE.MeshStandardMaterial
    black_910: THREE.MeshStandardMaterial
    sink_chrome: THREE.MeshStandardMaterial
    sink_faiance: THREE.MeshStandardMaterial
    chrome_dark: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
    Cardboard: THREE.MeshStandardMaterial
    ['941']: THREE.MeshStandardMaterial
    None_943: THREE.MeshStandardMaterial
    Glass_sweethome3d_window_mirror_985: THREE.MeshStandardMaterial
    Frame_out_frame_out_986: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    flgrey: THREE.MeshStandardMaterial
    polotence_polot_1017: THREE.MeshStandardMaterial
    ['1018']: THREE.MeshStandardMaterial
    bottom_bottom_1059: THREE.MeshStandardMaterial
    bottom_bottom_1152: THREE.MeshStandardMaterial
    bottom_bottom_1182: THREE.MeshStandardMaterial
    bottom_bottom_1212: THREE.MeshStandardMaterial
  }
}

type MaterialKeys = keyof GLTFResult['materials']

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './models/house-water-transformed.glb'
  ) as GLTFResult

  Object.keys(materials).forEach((m) => {
    if (!['sink_faiance', 'white_409', 'Ceramic'].includes(m)) {
      materials[m as MaterialKeys].flatShading = true
    }
  })

  return (
    <group {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        onPointerDown={(e) => {
          console.log(
            ((e.object as THREE.Mesh).material as THREE.MeshStandardMaterial)
              .name
          )
        }}
      >
        <mesh
          geometry={nodes['house_water-2_1'].geometry}
          material={materials.ground_1}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_2'].geometry}
          material={materials.wall_1_2}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_3'].geometry}
          material={materials.room_58_344}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_4'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_5'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_6'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_7'].geometry}
          material={materials['390']}
        />
        <mesh
          geometry={nodes['house_water-2_8'].geometry}
          material={materials['396']}
        />
        <mesh
          geometry={nodes['house_water-2_9'].geometry}
          material={materials['396']}
        />
        <mesh
          geometry={nodes['house_water-2_10'].geometry}
          material={materials['396']}
        />
        <mesh
          geometry={nodes['house_water-2_11'].geometry}
          material={materials['396']}
        />
        <mesh
          geometry={nodes['house_water-2_12'].geometry}
          material={materials['396']}
        />
        <mesh
          geometry={nodes['house_water-2_13'].geometry}
          material={materials.silver}
        />
        <mesh
          geometry={nodes['house_water-2_14'].geometry}
          material={materials.grey}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_15'].geometry}
          material={materials.flltgrey}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_16'].geometry}
          material={materials.ltgrey}
        />
        <mesh
          geometry={nodes['house_water-2_17'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_18'].geometry}
          material={materials.yellowbrt}
        />
        <mesh
          geometry={nodes['house_water-2_19'].geometry}
          material={materials.flltgrey_sweethome3d_window_pane_420}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_20'].geometry}
          material={materials['default']}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_21'].geometry}
          material={materials.lighttan}
        />
        <mesh
          geometry={nodes['house_water-2_22'].geometry}
          material={materials.white_Cube_2_1_433}
        />
        <mesh
          geometry={nodes['house_water-2_23'].geometry}
          material={materials.Glass}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_24'].geometry}
          material={materials.flltgrey_sweethome3d_window_pane_420}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_25'].geometry}
          material={materials.Lock}
        />
        <mesh
          geometry={nodes['house_water-2_26'].geometry}
          material={materials.Frame_in}
        />
        <mesh
          geometry={nodes['house_water-2_27'].geometry}
          material={materials.Frame_in}
        />
        <mesh
          geometry={nodes['house_water-2_28'].geometry}
          material={materials.wall_1_2}
        />
        <mesh
          geometry={nodes['house_water-2_29'].geometry}
          material={materials.wall_1_2}
        />
        <mesh
          geometry={nodes['house_water-2_30'].geometry}
          material={materials.flltgrey_sweethome3d_window_pane_420}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_31'].geometry}
          material={materials.white_Fenetre_480}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_32'].geometry}
          material={materials.None}
        />
        <mesh
          geometry={nodes['house_water-2_33'].geometry}
          material={materials.white_13_526}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_34'].geometry}
          material={materials.flltgrey_sweethome3d_window_pane_420}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_35'].geometry}
          material={materials.wall_1_2}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_36'].geometry}
          material={materials.flesh}
        />
        <mesh
          geometry={nodes['house_water-2_37'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_38'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_39'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_40'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_41'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_42'].geometry}
          material={materials.white_409}
        />
        <mesh
          geometry={nodes['house_water-2_43'].geometry}
          material={materials.glassblutint}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_44'].geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes['house_water-2_45'].geometry}
          material={materials.cuero_granate}
        />
        <mesh
          geometry={nodes['house_water-2_46'].geometry}
          material={materials.patas_metal}
        />
        <mesh
          geometry={nodes['house_water-2_47'].geometry}
          material={materials.brown}
        />
        <mesh
          geometry={nodes['house_water-2_48'].geometry}
          material={materials.black_615}
        />
        <mesh
          geometry={nodes['house_water-2_49'].geometry}
          material={materials.white_618}
        />
        <mesh
          geometry={nodes['house_water-2_50'].geometry}
          material={materials.Oriental_rug}
        />
        <mesh
          geometry={nodes['house_water-2_51'].geometry}
          material={materials.carpet_627}
        />
        <mesh
          geometry={nodes['house_water-2_52'].geometry}
          material={materials.gray}
        />
        <mesh
          geometry={nodes['house_water-2_53'].geometry}
          material={materials.Bathmat}
        />
        <mesh
          geometry={nodes['house_water-2_54'].geometry}
          material={materials.flbrown}
        />
        <mesh
          geometry={nodes['house_water-2_55'].geometry}
          material={materials.brownskn}
        />
        <mesh
          geometry={nodes['house_water-2_56'].geometry}
          material={materials['636']}
        />
        <mesh
          geometry={nodes['house_water-2_57'].geometry}
          material={materials.Material_LakeMoraine}
        />
        <mesh
          geometry={nodes['house_water-2_58'].geometry}
          material={materials.Aluminium}
        />
        <mesh
          geometry={nodes['house_water-2_59'].geometry}
          material={materials['640']}
        />
        <mesh
          geometry={nodes['house_water-2_60'].geometry}
          material={materials['643']}
        />
        <mesh
          geometry={nodes['house_water-2_61'].geometry}
          material={materials.Picture_1}
        />
        <mesh
          geometry={nodes['house_water-2_62'].geometry}
          material={materials.Picture_5}
        />
        <mesh
          geometry={nodes['house_water-2_63'].geometry}
          material={materials['651']}
        />
        <mesh
          geometry={nodes['house_water-2_64'].geometry}
          material={materials.Aluminium_652}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_65'].geometry}
          material={materials.Material_Etretat}
        />
        <mesh
          geometry={nodes['house_water-2_66'].geometry}
          material={materials.black_656}
        />
        <mesh
          geometry={nodes['house_water-2_67'].geometry}
          material={materials.cueEnd}
        />
        <mesh
          geometry={nodes['house_water-2_68'].geometry}
          material={materials['658']}
        />
        <mesh
          geometry={nodes['house_water-2_69'].geometry}
          material={materials.cueFront}
        />
        <mesh
          geometry={nodes['house_water-2_70'].geometry}
          material={materials.cueBrass}
        />
        <mesh
          geometry={nodes['house_water-2_71'].geometry}
          material={materials.cueBrass}
        />
        <mesh
          geometry={nodes['house_water-2_72'].geometry}
          material={materials.cueRubber}
        />
        <mesh
          geometry={nodes['house_water-2_73'].geometry}
          material={materials.cueTip}
        />
        <mesh
          geometry={nodes['house_water-2_74'].geometry}
          material={materials.ballCue}
        />
        <mesh
          geometry={nodes['house_water-2_75'].geometry}
          material={materials.ballN1}
        />
        <mesh
          geometry={nodes['house_water-2_76'].geometry}
          material={materials.ballN2}
        />
        <mesh
          geometry={nodes['house_water-2_77'].geometry}
          material={materials.ballN3}
        />
        <mesh
          geometry={nodes['house_water-2_78'].geometry}
          material={materials.ballN4}
        />
        <mesh
          geometry={nodes['house_water-2_79'].geometry}
          material={materials.ballN5}
        />
        <mesh
          geometry={nodes['house_water-2_80'].geometry}
          material={materials.ballN6}
        />
        <mesh
          geometry={nodes['house_water-2_81'].geometry}
          material={materials.ballN7}
        />
        <mesh
          geometry={nodes['house_water-2_82'].geometry}
          material={materials.ballN8}
        />
        <mesh
          geometry={nodes['house_water-2_83'].geometry}
          material={materials.ballN9}
        />
        <mesh
          geometry={nodes['house_water-2_84'].geometry}
          material={materials.ballN10}
        />
        <mesh
          geometry={nodes['house_water-2_85'].geometry}
          material={materials.ballN11}
        />
        <mesh
          geometry={nodes['house_water-2_86'].geometry}
          material={materials.ballN15}
        />
        <mesh
          geometry={nodes['house_water-2_87'].geometry}
          material={materials.ballN14}
        />
        <mesh
          geometry={nodes['house_water-2_88'].geometry}
          material={materials.ballN13}
        />
        <mesh
          geometry={nodes['house_water-2_89'].geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes['house_water-2_90'].geometry}
          material={materials.ballN12}
        />
        <mesh
          geometry={nodes['house_water-2_91'].geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes['house_water-2_92'].geometry}
          material={materials.felt}
        />
        <mesh
          geometry={nodes['house_water-2_93'].geometry}
          material={materials.GrisClair}
        />
        <mesh
          geometry={nodes['house_water-2_94'].geometry}
          material={materials.BoisClair}
        />
        <mesh
          geometry={nodes['house_water-2_95'].geometry}
          material={materials.wall_1_2}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_96'].geometry}
          material={materials['636']}
        />
        <mesh
          geometry={nodes['house_water-2_97'].geometry}
          material={materials.METAL_brass_polish}
        />
        <mesh
          geometry={nodes['house_water-2_98'].geometry}
          material={materials.METAL_aluminum}
        />
        <mesh
          geometry={nodes['house_water-2_99'].geometry}
          material={materials.GLASS}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_100'].geometry}
          material={materials.PAINT_gloss_white}
        />
        <mesh
          geometry={nodes['house_water-2_101'].geometry}
          material={materials.METAL_brass_polish}
        />
        <mesh
          geometry={nodes['house_water-2_102'].geometry}
          material={materials.METAL_brass_polish}
        />
        <mesh
          geometry={nodes['house_water-2_103'].geometry}
          material={materials.Feet}
        />
        <mesh
          geometry={nodes['house_water-2_104'].geometry}
          material={materials.Material_Cube_787}
        />
        <mesh
          geometry={nodes['house_water-2_105'].geometry}
          material={materials.sofa}
        />
        <mesh
          geometry={nodes['house_water-2_106'].geometry}
          material={materials.negrepotes}
        />
        <mesh
          geometry={nodes['house_water-2_107'].geometry}
          material={materials.metall}
        />
        <mesh
          geometry={nodes['house_water-2_108'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_109'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_110'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_111'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_112'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_113'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_114'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_115'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_116'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_117'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_118'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_119'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_120'].geometry}
          material={materials.Railing}
        />
        <mesh
          geometry={nodes['house_water-2_121'].geometry}
          material={materials.archwhite}
        />
        <mesh
          geometry={nodes['house_water-2_122'].geometry}
          material={materials.sweethome3d_window_mirror_902}
        />
        <mesh
          geometry={nodes['house_water-2_123'].geometry}
          material={materials.aqua}
        />
        <mesh
          geometry={nodes['house_water-2_124'].geometry}
          material={materials.Rectangle04_1}
        />
        <mesh
          geometry={nodes['house_water-2_125'].geometry}
          material={materials.black_910}
        />
        <mesh
          geometry={nodes['house_water-2_126'].geometry}
          material={materials.sink_chrome}
        />
        <mesh
          geometry={nodes['house_water-2_127'].geometry}
          material={materials.sink_faiance}
        />
        <mesh
          geometry={nodes['house_water-2_128'].geometry}
          material={materials.chrome_dark}
        />
        <mesh
          geometry={nodes['house_water-2_129'].geometry}
          material={materials.patas_metal}
        />
        <mesh
          geometry={nodes['house_water-2_130'].geometry}
          material={materials.PAINT_gloss_white}
        />
        <mesh
          geometry={nodes['house_water-2_131'].geometry}
          material={materials.paper}
        />
        <mesh
          geometry={nodes['house_water-2_132'].geometry}
          material={materials.Cardboard}
        />
        <mesh
          geometry={nodes['house_water-2_133'].geometry}
          material={materials['941']}
        />
        <mesh
          geometry={nodes['house_water-2_134'].geometry}
          material={materials.sink_chrome}
        />
        <mesh
          geometry={nodes['house_water-2_135'].geometry}
          material={materials.None_943}
        />
        <mesh
          geometry={nodes['house_water-2_136'].geometry}
          material={materials['941']}
        />
        <mesh
          geometry={nodes['house_water-2_137'].geometry}
          material={materials.sink_chrome}
        />
        <mesh
          geometry={nodes['house_water-2_138'].geometry}
          material={materials.sink_faiance}
        />
        <mesh
          geometry={nodes['house_water-2_139'].geometry}
          material={materials.PAINT_gloss_white}
        />
        <mesh
          geometry={nodes['house_water-2_140'].geometry}
          material={materials.Glass_sweethome3d_window_mirror_985}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
        <mesh
          geometry={nodes['house_water-2_141'].geometry}
          material={materials.Frame_out_frame_out_986}
        />
        <mesh
          geometry={nodes['house_water-2_142'].geometry}
          material={materials.wall_1_2}
        />
        <mesh
          geometry={nodes['house_water-2_143'].geometry}
          material={materials.red}
        />
        <mesh
          geometry={nodes['house_water-2_144'].geometry}
          material={materials.flgrey}
        />
        <mesh
          geometry={nodes['house_water-2_145'].geometry}
          material={materials.ballCue}
        />
        <mesh
          geometry={nodes['house_water-2_146'].geometry}
          material={materials.polotence_polot_1017}
        />
        <mesh
          geometry={nodes['house_water-2_147'].geometry}
          material={materials['1018']}
        />
        <mesh
          geometry={nodes['house_water-2_148'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_149'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_150'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_151'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_152'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_153'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_154'].geometry}
          material={materials.bottom_bottom_1059}
        />
        <mesh
          geometry={nodes['house_water-2_155'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_156'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_157'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_158'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_159'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_160'].geometry}
          material={materials.bottom_bottom_1152}
        />
        <mesh
          geometry={nodes['house_water-2_161'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_162'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_163'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_164'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_165'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_166'].geometry}
          material={materials.bottom_bottom_1182}
        />
        <mesh
          geometry={nodes['house_water-2_167'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_168'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_169'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_170'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_171'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_172'].geometry}
          material={materials.bottom_bottom_1212}
        />
        <mesh
          geometry={nodes['house_water-2_173'].geometry}
          material={materials.bottom_bottom_1212}
          material-transparent
          material-opacity={0.2}
          material-depthWrite={false}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/house-water-transformed.glb')
